name: Site Test Build

on:
  pull_request:
    branches: [main]

jobs:
  site-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
      - name: Test Build Scripts
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build-repo-data
          npm run build-posts-data
      - name: Test Build
        run: npm run build
